version: "3"
services:
  my-app:
    build:
      context: ./my-app
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    volumes:
      - "./my-app:/usr/src/app"
    depends_on:
      - php-app

  php-app:
    build:
      context: ./php-app
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - "./php-app:/var/www/html"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword

  mysql:
    build: ./mysql/
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=zanpy
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
      - LANG=C.utf8
      - LC_ALL=C.utf8
