version: "3"
services:
  my-app:
    build:
      context: ./my-app
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    volumes:
      - "./my-app:/usr/src/app"
    depends_on:
      - php-app

  php-app:
    build:
      context: ./php-app
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - "./php-app:/var/www/html"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - ./mysql-data:/var/lib/mysql
